[server]
headless = true

maxUploadSize = 200


[client]
showErrorDetails = false

[theme]
primaryColor = "#ff6b6b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
